{ pkgs, ... }:
{
  home.packages = with pkgs; [
    (agda.withPackages [ agdaPackages.standard-library ])
    audacity
    bat
    cabal2nix
    cargo
    clippy
    cloc
    cron
    distrobox
    dmenu
    edir
    eza
    feh
    ffmpeg
    firefox
    fzf
    gcc
    gh
    ghc
    ghcid
    glow
    gnumake
    hack-font
    haskell-language-server
    haskellPackages.cabal-fmt
    haskellPackages.cabal-install
    haskellPackages.fast-tags
    haskellPackages.hoogle
    haskellPackages.patat
    haskellPackages.stack
    haskellPackages.stylish-haskell
    hlint
    htop
    just
    libreoffice
    lua-language-server
    man-pages
    man-pages-posix
    marksman
    neofetch
    nerdfonts
    nil
    nix-prefetch-git
    nixos-option
    nixpkgs-fmt
    nixpkgs-lint
    obs-studio
    pandoc
    pcmanfm
    python3
    qbittorrent
    ripgrep
    rlwrap
    roboto
    rust-analyzer
    rustc
    rustfmt
    spotify
    spotify-player
    stylua
    texlive.combined.scheme-full
    thunderbird
    tldr
    tree
    typst
    typst-lsp
    typstfmt
    unzip
    vlc
    vscode
    webcord
    wget
    xclip
    xorg.xhost
    zip
    zlib
    zlib.dev
    zoom-us
  ];
}
